+ Common
menu = Common
title = Common Services


++ Facebook
menu = Facebook
title = facebook.com
host = facebook.com

++ Google
menu = Google
title = google.com
host = google.com

++ Steam
menu = Steam
title = Steam

+++ Community
menu = Community
title = steamcommunity.com
host = steamcommunity.com

+++ Store
menu = Store
title = store.steampowered.com
host = store.steampowered.com

++ Twitter
menu = Twitter
title = twitter.com
host = twitter.com

++ Wikipedia_EN
menu = Wikipedia (EN)
title = en.wikipedia.org
host = en.wikipedia.org

++ WordPress
menu = WordPress
title = wordpress.com
host = wordpress.com

++ YouTube
menu = YouTube
title = youtube.com
host = youtube.com
