++ CloudflareDNS1
probe = DNS
menu = Cloudflare - Primary
title = Cloudflare DNS - Primary (1.1.1.1)
host = 1.1.1.1
lookup = example.com

++ CloudflareDNS2
probe = DNS
menu = Cloudflare - Secondary
title = Cloudflare DNS - Secondary (1.0.0.1)
host = 1.0.0.1
lookup = example.com

++ GoogleDNS1
probe = DNS
menu = Google - Primary
title = Google DNS - Primary (8.8.8.8)
host = 8.8.8.8
lookup = example.com

++ GoogleDNS2
probe = DNS
menu = Google - Secondary
title = Google DNS - Secondary (8.8.4.4)
host = 8.8.4.4
lookup = example.com

++ OpenDNS1
probe = DNS
menu = OpenDNS - Primary
title = OpenDNS - Primary (208.67.222.222)
host = 208.67.222.222
lookup = example.com

++ OpenDNS2
probe = DNS
menu = OpenDNS - Secondary
title = OpenDNS - Secondary (208.67.220.220)
host = 208.67.220.220
lookup = example.com

++ Quad9
probe = DNS
menu = Quad9 - Primary
title = Quad9 DNS - Primary (9.9.9.9)
host = 9.9.9.9
lookup = example.com

++ Quad92
probe = DNS
menu = Quad9 - Secondary
title = Quad9 DNS - Secondary (149.112.112.112)
host = 149.112.112.112
lookup = example.com

++ NextDNS1
probe = DNS
menu = NextDNS - Primary
title = NextDNS - Primary (45.90.28.190)
host = 45.90.28.190
lookup = example.com

++ NextDNS2
probe = DNS
menu = NextDNS - Secondary
title = NextDNS - Secondary (45.90.30.190)
host = 45.90.30.190
lookup = example.com

++ AdGuardDNS1
probe = DNS
menu = AdGuard - Primary
title = AdGuard DNS - Primary (94.140.14.14)
host = 94.140.14.14
lookup = example.com

++ AdGuardDNS2
probe = DNS
menu = AdGuard - Secondary
title = AdGuard DNS - Secondary (94.140.15.15)
host = 94.140.15.15
lookup = example.com

++ Level3DNS1
probe = DNS
menu = Level3 - Primary
title = Level3 DNS - Primary (4.2.2.1)
host = 4.2.2.1
lookup = example.com

++ Level3DNS2
probe = DNS
menu = Level3 - Secondary
title = Level3 DNS - Secondary (4.2.2.2)
host = 4.2.2.2
lookup = example.com

++ CleanBrowsingDNS1
probe = DNS
menu = CleanBrowsing - Primary
title = CleanBrowsing DNS - Primary (185.228.168.9)
host = 185.228.168.9
lookup = example.com

++ CleanBrowsingDNS2
probe = DNS
menu = CleanBrowsing - Secondary
title = CleanBrowsing DNS - Secondary (185.228.169.9)
host = 185.228.169.9
lookup = example.com
