++ CloudflareDNS1v6
probe = FPing6
menu = Cloudflare - Primary (IPv6)
title = Cloudflare DNS - Primary (2606:4700:4700::1111)
host = 2606:4700:4700::1111

++ CloudflareDNS2v6
probe = FPing6
menu = Cloudflare - Secondary (IPv6)
title = Cloudflare DNS - Secondary (2606:4700:4700::1001)
host = 2606:4700:4700::1001

++ GoogleDNS1v6
probe = FPing6
menu = Google - Primary (IPv6)
title = Google DNS - Primary (2001:4860:4860::8888)
host = 2001:4860:4860::8888

++ GoogleDNS2v6
probe = FPing6
menu = Google - Secondary (IPv6)
title = Google DNS - Secondary (2001:4860:4860::8844)
host = 2001:4860:4860::8844

++ OpenDNS1v6
probe = FPing6
menu = OpenDNS - Primary (IPv6)
title = OpenDNS - Primary (2620:119:35::35)
host = 2620:119:35::35

++ OpenDNS2v6
probe = FPing6
menu = OpenDNS - Secondary (IPv6)
title = OpenDNS - Secondary (2620:119:53::53)
host = 2620:119:53::53

++ Quad9v6
probe = FPing6
menu = Quad9 - Primary (IPv6)
title = Quad9 DNS - Primary (2620:fe::fe)
host = 2620:fe::fe

++ Quad92v6
probe = FPing6
menu = Quad9 - Secondary (IPv6)
title = Quad9 DNS - Secondary (2620:fe::9)
host = 2620:fe::9

++ AdGuardDNS1v6
probe = FPing6
menu = AdGuard - Primary (IPv6)
title = AdGuard DNS - Primary (2a10:50c0::ad1:ff)
host = 2a10:50c0::ad1:ff

++ AdGuardDNS2v6
probe = FPing6
menu = AdGuard - Secondary (IPv6)
title = AdGuard DNS - Secondary (2a10:50c0::ad2:ff)
host = 2a10:50c0::ad2:ff

++ CleanBrowsingDNS1v6
probe = FPing6
menu = CleanBrowsing - Primary (IPv6)
title = CleanBrowsing DNS - Primary (2a0d:2a00:1::2)
host = 2a0d:2a00:1::2

++ CleanBrowsingDNS2v6
probe = FPing6
menu = CleanBrowsing - Secondary (IPv6)
title = CleanBrowsing DNS - Secondary (2a0d:2a00:2::2)
host = 2a0d:2a00:2::2

++ ControlD1v6
probe = FPing6
menu = Control D - Primary (IPv6)
title = Control D DNS - Primary (2606:1a40::)
host = 2606:1a40::

++ ControlD2v6
probe = FPing6
menu = Control D - Secondary (IPv6)
title = Control D DNS - Secondary (2606:1a40:1::)
host = 2606:1a40:1::

++ Mullvadv6
probe = FPing6
menu = Mullvad (IPv6)
title = Mullvad DNS (2a07:e340::2)
host = 2a07:e340::2
