++ CloudflareDNS1
menu = Cloudflare - Primary
title = Cloudflare DNS - Primary (1.1.1.1)
host = 1.1.1.1

++ CloudflareDNS2
menu = Cloudflare - Secondary
title = Cloudflare DNS - Secondary (1.0.0.1)
host = 1.0.0.1

++ GoogleDNS1
menu = Google - Primary
title = Google DNS - Primary (8.8.8.8)
host = 8.8.8.8

++ GoogleDNS2
menu = Google - Secondary
title = Google DNS - Secondary (8.8.4.4)
host = 8.8.4.4

++ OpenDNS1
menu = OpenDNS - Primary
title = OpenDNS - Primary (208.67.222.222)
host = 208.67.222.222

++ OpenDNS2
menu = OpenDNS - Secondary
title = OpenDNS - Secondary (208.67.220.220)
host = 208.67.220.220

++ Quad9
menu = Quad9 - Primary
title = Quad9 DNS - Primary (9.9.9.9)
host = 9.9.9.9

++ Quad92
menu = Quad9 - Secondary
title = Quad9 DNS - Secondary (149.112.112.112)
host = 149.112.112.112

++ NextDNS1
menu = NextDNS - Primary
title = NextDNS - Primary (45.90.28.190)
host = 45.90.28.190

++ NextDNS2
menu = NextDNS - Secondary
title = NextDNS - Secondary (45.90.30.190)
host = 45.90.30.190

++ AdGuardDNS1
menu = AdGuard - Primary
title = AdGuard DNS - Primary (94.140.14.14)
host = 94.140.14.14

++ AdGuardDNS2
menu = AdGuard - Secondary
title = AdGuard DNS - Secondary (94.140.15.15)
host = 94.140.15.15

++ Level3DNS1
menu = Level3 - Primary
title = Level3 DNS - Primary (4.2.2.1)
host = 4.2.2.1

++ Level3DNS2
menu = Level3 - Secondary
title = Level3 DNS - Secondary (4.2.2.2)
host = 4.2.2.2

++ CleanBrowsingDNS1
menu = CleanBrowsing - Primary
title = CleanBrowsing DNS - Primary (185.228.168.9)
host = 185.228.168.9

++ CleanBrowsingDNS2
menu = CleanBrowsing - Secondary
title = CleanBrowsing DNS - Secondary (185.228.169.9)
host = 185.228.169.9
