+ Geo
menu = Geo
title = Geographic Targets


++ Europe
menu = Europe
title = European Connectivity

+++ CIXP
menu = CH - CIXP
title = CERN Internet eXchange Point (Switzerland)
host = cixp.web.cern.ch

+++ Telefonica
menu = DE - Telefonica
title = Telefonica (Germany)
host = www.telefonica.de

+++ Cambridge
menu = UK - Cambridge
title = Cambridge University (United Kingdom)
host = cam.ac.uk


++ Oceania
menu = Oceania
title = Oceanic Connectivity

+++ FSMG_HLZMEL
menu = NZ - FSMG - HLZMEL
title = hlzmel.fsmg.org.nz
host = hlzmel.fsmg.org.nz

+++ FSMG_WLGLAM
menu = NZ - FSMG - WLGLAM
title = wlglam.fsmg.org.nz
host = wlglam.fsmg.org.nz

+++ GoogleNZ
menu = NZ - Google
title = google.co.nz
host = google.co.nz

+++ TradeMe
menu = NZ - TradeMe
title = trademe.co.nz
host = trademe.co.nz


++ NorthAmerica
menu = North America
title = North American Connectivity

+++ OSUOSL
menu = US - OSUOSL
title = Oregon State University Open Source Lab (United States of America)
host = osuosl.org

+++ UMN
menu = US - UMN
title = University of Minnesota Twin Cities (United States of America)
host = twin-cities.umn.edu

# TODO
#host = ucsd.edu
#host = web.mit.edu
#host = www.berkeley.edu
#host = www.indiana.edu
