+ Geo
menu = Geo
title = Geographic Targets


++ Europe
menu = Europe
title = European Connectivity

+++ CIXP
menu = CH - CIXP
title = CERN Internet eXchange Point (Switzerland)
host = cixp.web.cern.ch

+++ Telefonica
menu = DE - Telefonica
title = Telefonica (Germany)
host = www.telefonica.de

+++ Cambridge
menu = UK - Cambridge
title = Cambridge University (UK)
host = cam.ac.uk


++ NorthAmerica
menu = North America
title = North American Connectivity

+++ UBC
menu = CA - BC - UBC
title = University of British Columbia (British Columbia, Canada)
host = mirror.it.ubc.ca

+++ Waterloo
menu = CA - ON - Waterloo
title = University of Waterloo (Ontario, Canada)
host = mirror.csclub.uwaterloo.ca

+++ Berkeley
menu = US - CA - Berkeley
title = UC Berkeley (California, USA)
host = mirrors.ocf.berkeley.edu

+++ Stanford
menu = US - CA - Stanford
title = Stanford University (California, USA)
host = www.stanford.edu

+++ UCSD
menu = US - CA - UCSD
title = UC San Diego (California, USA)
host = ucsd.edu

+++ Indiana
menu = US - IN - IU
title = Indiana University Bloomington (Indiana, USA)
host = www.indiana.edu

+++ MIT
menu = US - MA - MIT
title = Massachusetts Institute of Technology (Massachusetts, USA)
host = web.mit.edu

+++ UMN
menu = US - MN - UMN
title = University of Minnesota Twin Cities (Minnesota, USA)
host = twin-cities.umn.edu

+++ OSUOSL
menu = US - OR - OSUOSL
title = Oregon State University Open Source Lab (Oregon, USA)
host = osuosl.org


++ Oceania
menu = Oceania
title = Oceanic Connectivity

+++ AARNet
menu = AU - AARNet
title = mirror.aarnet.edu.au
host = mirror.aarnet.edu.au

+++ FSMG_HLZMEL
menu = NZ - FSMG - HLZMEL
title = hlzmel.fsmg.org.nz
host = hlzmel.fsmg.org.nz

+++ FSMG_WLGLAM
menu = NZ - FSMG - WLGLAM
title = wlglam.fsmg.org.nz
host = wlglam.fsmg.org.nz

+++ GoogleNZ
menu = NZ - Google
title = google.co.nz
host = google.co.nz

+++ TradeMe
menu = NZ - TradeMe
title = trademe.co.nz
host = trademe.co.nz
