@include /config/Smokeping-Configs/local.conf
@include /config/Smokeping-Configs/quic.conf
@include /config/Smokeping-Configs/dns.conf
@include /config/Smokeping-Configs/common.conf
@include /config/Smokeping-Configs/geo.conf
@include /config/Smokeping-Configs/alibaba.conf
@include /config/Smokeping-Configs/amazonaws.conf
@include /config/Smokeping-Configs/amazonaws_generated.conf
@include /config/Smokeping-Configs/apple.conf
@include /config/Smokeping-Configs/linode.conf
@include /config/Smokeping-Configs/oraclecloud.conf
@include /config/Smokeping-Configs/ovh.conf
@include /config/Smokeping-Configs/vultr.conf
